---
- name: 'Fail when mmonit_admin_password or mmonit_connector_password is empty'
  assert:
    that:
      - "mmonit_admin_password != ''"
      - "mmonit_connector_password != ''"

- name: 'Check if setup is required'
  register: _mmonit_setup
  stat:
    path: '/etc/.mmonit_installed'

- name: 'Generate setup script'
  when: _mmonit_setup.stat.exists is not defined or _mmonit_setup.stat.exists == false
  template:
    src: 'setup.sh'
    dest: '/opt/ansibe-mmonit.sh'
    mode: '0700'
    owner: 'root'
    group: 'root'

- name: 'Run script'
  when: _mmonit_setup.stat.exists is not defined or _mmonit_setup.stat.exists == false
  shell: '/opt/ansibe-mmonit.sh'
  tags: ['skip_ansible_lint']

- name: 'Cleanup'
  when: _mmonit_setup.stat.exists is not defined or _mmonit_setup.stat.exists == false
  file:
    path: '/opt/ansibe-mmonit.sh'
    state: absent

