---
- name: start mmonit
  notify: 'Check M/Monit'
  service:
    name: 'monit'
    state: started
    enabled: yes

- name: restart mmonit
  notify: 'Check M/Monit'
  service:
    name: 'mmonit'
    state: restarted
    enabled: yes

- name: reload systemd
  command: systemctl daemon-reload

- name: reload initctl
  command: initctl reload-configuration

- name: 'Check M/Monit'
  shell: "[ $({{ mmonit_executable }} --version | cut -d ' ' -f 1 | cut -d '/' -f2) == '{{ mmonit_version }}' ]"
